[
  {
    distanceFromSearch: '0.1km',
    mls: '40177708',
    mlsUrl: '',
    status: 'A',
    currentPrice: 399000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '18 HUNTLEY Street',
    city: 'Hamilton',
    beds: '(4+0)',
    baths: '(1+1)',
    sqftAboveGround: 1650,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 502333.3333333333,
    discountFromAverageHomePrice: '21%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40175916',
    mlsUrl: '',
    status: 'A',
    currentPrice: 699900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '11 CAIRNS Avenue',
    city: 'Dundas',
    beds: '(2+1)',
    baths: '(2+0)',
    sqftAboveGround: 780,
    sqftBelowGround: 470,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 945000,
    discountFromAverageHomePrice: '26%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40177708',
    mlsUrl: '',
    status: 'A',
    currentPrice: 399000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '18 HUNTLEY Street',
    city: 'Hamilton',
    beds: '(4+0)',
    baths: '(1+1)',
    sqftAboveGround: 1650,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 571750,
    discountFromAverageHomePrice: '30%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40177708',
    mlsUrl: '',
    status: 'A',
    currentPrice: 399000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '18 HUNTLEY Street',
    city: 'Hamilton',
    beds: '(4+0)',
    baths: '(1+1)',
    sqftAboveGround: 1650,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 571750,
    discountFromAverageHomePrice: '30%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40175916',
    mlsUrl: '',
    status: 'A',
    currentPrice: 699900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '11 CAIRNS Avenue',
    city: 'Dundas',
    beds: '(2+1)',
    baths: '(2+0)',
    sqftAboveGround: 780,
    sqftBelowGround: 470,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 945000,
    discountFromAverageHomePrice: '26%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40177206',
    mlsUrl: '',
    status: 'A',
    currentPrice: 549900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '215 EAST 33RD Street',
    city: 'Hamilton',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1090,
    sqftBelowGround: 300,
    daysOnMarket: 3,
    averageHomePriceInTheArea: 782000,
    discountFromAverageHomePrice: '30%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40175800',
    mlsUrl: '',
    status: 'A',
    currentPrice: 599000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '207 EAST 8TH Avenue',
    city: 'Hamilton',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 931,
    sqftBelowGround: null,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 812750,
    discountFromAverageHomePrice: '26%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40175800',
    mlsUrl: '',
    status: 'A',
    currentPrice: 599000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '207 EAST 8TH Avenue',
    city: 'Hamilton',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 931,
    sqftBelowGround: null,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 980000,
    discountFromAverageHomePrice: '39%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40177708',
    mlsUrl: '',
    status: 'A',
    currentPrice: 399000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '18 HUNTLEY Street',
    city: 'Hamilton',
    beds: '(4+0)',
    baths: '(1+1)',
    sqftAboveGround: 1650,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 501750,
    discountFromAverageHomePrice: '20%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40175916',
    mlsUrl: '',
    status: 'A',
    currentPrice: 699900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '11 CAIRNS Avenue',
    city: 'Dundas',
    beds: '(2+1)',
    baths: '(2+0)',
    sqftAboveGround: 780,
    sqftBelowGround: 470,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 945000,
    discountFromAverageHomePrice: '26%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40175357',
    mlsUrl: '',
    status: 'A',
    currentPrice: 699000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '75 BAYVIEW Drive',
    city: 'St. Catharines',
    beds: '(2+1)',
    baths: '(2+0)',
    sqftAboveGround: 1090,
    sqftBelowGround: null,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 944983.3333333334,
    discountFromAverageHomePrice: '26%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40175926',
    mlsUrl: '',
    status: 'A',
    currentPrice: 399900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '6549 HIGH Street',
    city: 'Niagara Falls',
    beds: '(2+0)',
    baths: '(1+1)',
    sqftAboveGround: 1100,
    sqftBelowGround: null,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 586357.1428571428,
    discountFromAverageHomePrice: '32%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40177188',
    mlsUrl: '',
    status: 'A',
    currentPrice: 339000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '4352 ELGIN Street',
    city: 'Niagara Falls',
    beds: '(1+0)',
    baths: '(1+0)',
    sqftAboveGround: 500,
    sqftBelowGround: null,
    daysOnMarket: 3,
    averageHomePriceInTheArea: 443000,
    discountFromAverageHomePrice: '23%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40176750',
    mlsUrl: '',
    status: 'A',
    currentPrice: 549900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '160 GLENDALE Avenue',
    city: 'St. Catharines',
    beds: '(2+1)',
    baths: '(1+0)',
    sqftAboveGround: 1000,
    sqftBelowGround: null,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 726900,
    discountFromAverageHomePrice: '24%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40177453',
    mlsUrl: '',
    status: 'A',
    currentPrice: 499900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '6742 DUNN Street',
    city: 'Niagara Falls',
    beds: '(2+0)',
    baths: '(1+1)',
    sqftAboveGround: 1320,
    sqftBelowGround: null,
    daysOnMarket: 3,
    averageHomePriceInTheArea: 637728.5714285715,
    discountFromAverageHomePrice: '22%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40173028',
    mlsUrl: '',
    status: 'A',
    currentPrice: 449900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '37 DONCASTER Boulevard',
    city: 'St. Catharines',
    beds: '(2+1)',
    baths: '(1+0)',
    sqftAboveGround: 630,
    sqftBelowGround: null,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 590000,
    discountFromAverageHomePrice: '24%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40164453',
    mlsUrl: '',
    status: 'A',
    currentPrice: 549000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '7 GLEN Avenue',
    city: 'St. Catharines',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1100,
    sqftBelowGround: 1000,
    daysOnMarket: 3,
    averageHomePriceInTheArea: 782499.5,
    discountFromAverageHomePrice: '30%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40169933',
    mlsUrl: '',
    status: 'A',
    currentPrice: 590000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '13 HOWARD Avenue',
    city: 'St. Catharines',
    beds: '(3+0)',
    baths: '(1+0)',
    sqftAboveGround: 1086,
    sqftBelowGround: 526,
    daysOnMarket: 3,
    averageHomePriceInTheArea: 857500,
    discountFromAverageHomePrice: '31%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40176255',
    mlsUrl: '',
    status: 'A',
    currentPrice: 399800,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '6280 COLBORNE Street',
    city: 'Niagara Falls',
    beds: '(3+1)',
    baths: '(1+1)',
    sqftAboveGround: 1034,
    sqftBelowGround: null,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 596883.3333333334,
    discountFromAverageHomePrice: '33%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40176682',
    mlsUrl: '',
    status: 'A',
    currentPrice: 399900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '6139 FRANKLIN Avenue',
    city: 'Niagara Falls',
    beds: '(2+0)',
    baths: '(1+0)',
    sqftAboveGround: 875,
    sqftBelowGround: null,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 541076,
    discountFromAverageHomePrice: '26%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40170892',
    mlsUrl: '',
    status: 'A',
    currentPrice: 359900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '41 ALEXANDER Street',
    city: 'Welland',
    beds: '(2+0)',
    baths: '(1+1)',
    sqftAboveGround: 876,
    sqftBelowGround: null,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 480010,
    discountFromAverageHomePrice: '25%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40177644',
    mlsUrl: '',
    status: 'A',
    currentPrice: 399900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '19 VICTORIA Street',
    city: 'Port Colborne',
    beds: '(1+0)',
    baths: '(1+0)',
    sqftAboveGround: 600,
    sqftBelowGround: null,
    daysOnMarket: 2,
    averageHomePriceInTheArea: 667500,
    discountFromAverageHomePrice: '40%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40176682',
    mlsUrl: '',
    status: 'A',
    currentPrice: 399900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '6139 FRANKLIN Avenue',
    city: 'Niagara Falls',
    beds: '(2+0)',
    baths: '(1+0)',
    sqftAboveGround: 875,
    sqftBelowGround: null,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 570000,
    discountFromAverageHomePrice: '30%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40177188',
    mlsUrl: '',
    status: 'A',
    currentPrice: 339000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '4352 ELGIN Street',
    city: 'Niagara Falls',
    beds: '(1+0)',
    baths: '(1+0)',
    sqftAboveGround: 500,
    sqftBelowGround: null,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 490500,
    discountFromAverageHomePrice: '31%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40176750',
    mlsUrl: '',
    status: 'A',
    currentPrice: 549900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '160 GLENDALE Avenue',
    city: 'St. Catharines',
    beds: '(2+1)',
    baths: '(1+0)',
    sqftAboveGround: 1000,
    sqftBelowGround: null,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 698333.3333333334,
    discountFromAverageHomePrice: '21%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40178063',
    mlsUrl: '',
    status: 'A',
    currentPrice: 479900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '7385 FERN Avenue',
    city: 'Niagara Falls',
    beds: '(3+0)',
    baths: '(1+1)',
    sqftAboveGround: 950,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 610750,
    discountFromAverageHomePrice: '21%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40176682',
    mlsUrl: '',
    status: 'A',
    currentPrice: 399900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '6139 FRANKLIN Avenue',
    city: 'Niagara Falls',
    beds: '(2+0)',
    baths: '(1+0)',
    sqftAboveGround: 875,
    sqftBelowGround: null,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 541076,
    discountFromAverageHomePrice: '26%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40177188',
    mlsUrl: '',
    status: 'A',
    currentPrice: 339000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '4352 ELGIN Street',
    city: 'Niagara Falls',
    beds: '(1+0)',
    baths: '(1+0)',
    sqftAboveGround: 500,
    sqftBelowGround: null,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 427333.3333333333,
    discountFromAverageHomePrice: '21%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40170454',
    mlsUrl: '',
    status: 'A',
    currentPrice: 599900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '368 LAKESIDE Road',
    city: 'Fort Erie',
    beds: '(4+0)',
    baths: '(4+0)',
    sqftAboveGround: 2610,
    sqftBelowGround: null,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 1000000,
    discountFromAverageHomePrice: '40%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40176091',
    mlsUrl: '',
    status: 'A',
    currentPrice: 499900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '5965 CARLTON Avenue',
    city: 'Niagara Falls',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1329,
    sqftBelowGround: null,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 647250,
    discountFromAverageHomePrice: '23%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40176727',
    mlsUrl: '',
    status: 'A',
    currentPrice: 829900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '172 HARDCASTLE Drive',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+2)',
    sqftAboveGround: 1350,
    sqftBelowGround: 600,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 1102333.3333333333,
    discountFromAverageHomePrice: '25%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40177453',
    mlsUrl: '',
    status: 'A',
    currentPrice: 499900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '6742 DUNN Street',
    city: 'Niagara Falls',
    beds: '(2+0)',
    baths: '(1+1)',
    sqftAboveGround: 1320,
    sqftBelowGround: null,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 633011.1111111111,
    discountFromAverageHomePrice: '21%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40178063',
    mlsUrl: '',
    status: 'A',
    currentPrice: 479900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '7385 FERN Avenue',
    city: 'Niagara Falls',
    beds: '(3+0)',
    baths: '(1+1)',
    sqftAboveGround: 950,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 635000,
    discountFromAverageHomePrice: '24%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40173544',
    mlsUrl: '',
    status: 'A',
    currentPrice: 889000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '8472 KELSEY Crescent',
    city: 'Niagara Falls',
    beds: '(4+2)',
    baths: '(3+1)',
    sqftAboveGround: 1760,
    sqftBelowGround: null,
    daysOnMarket: 1,
    averageHomePriceInTheArea: 1117813.3333333333,
    discountFromAverageHomePrice: '20%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40177643',
    mlsUrl: '',
    status: 'A',
    currentPrice: 549900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '831 SHERRING Street',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1656,
    sqftBelowGround: null,
    daysOnMarket: 1,
    averageHomePriceInTheArea: 738333.3333333334,
    discountFromAverageHomePrice: '26%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40177301',
    mlsUrl: '',
    status: 'A',
    currentPrice: 499999,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '840 GUELPH Street',
    city: 'Kitchener',
    beds: '(4+0)',
    baths: '(2+0)',
    sqftAboveGround: 1333,
    sqftBelowGround: 693,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 641500,
    discountFromAverageHomePrice: '22%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40161666',
    mlsUrl: '',
    status: 'A',
    currentPrice: 700000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '11 GLOUCESTER Court',
    city: 'Kitchener',
    beds: '(3+1)',
    baths: '(3+1)',
    sqftAboveGround: 1962,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 890500,
    discountFromAverageHomePrice: '21%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40176671',
    mlsUrl: '',
    status: 'A',
    currentPrice: 649900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '114 WILLIAM Street W',
    city: 'Waterloo',
    beds: '(2+0)',
    baths: '(1+2)',
    sqftAboveGround: 952,
    sqftBelowGround: 84,
    daysOnMarket: 1,
    averageHomePriceInTheArea: 1003333.3333333334,
    discountFromAverageHomePrice: '35%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40178341',
    mlsUrl: '',
    status: 'A',
    currentPrice: 579900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '459 RED RIVER Drive',
    city: 'Waterloo',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1150,
    sqftBelowGround: 190,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 760954.5454545454,
    discountFromAverageHomePrice: '24%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40177520',
    mlsUrl: '',
    status: 'A',
    currentPrice: 669000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '237A THISTLEGLEN Place',
    city: 'Waterloo',
    beds: '(3+0)',
    baths: '(1+1)',
    sqftAboveGround: 1177,
    sqftBelowGround: 230,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 995000,
    discountFromAverageHomePrice: '33%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40176618',
    mlsUrl: '',
    status: 'A',
    currentPrice: 869000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '269 RIDGEMERE Court',
    city: 'Kitchener',
    beds: '(3+1)',
    baths: '(3+0)',
    sqftAboveGround: 1715,
    sqftBelowGround: 1100,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 1341250,
    discountFromAverageHomePrice: '35%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40175735',
    mlsUrl: '',
    status: 'A',
    currentPrice: 500000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '69 FRANCIS Street',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(1+0)',
    sqftAboveGround: 1260,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 675000,
    discountFromAverageHomePrice: '26%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40178398',
    mlsUrl: '',
    status: 'A',
    currentPrice: 399000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '25 GRANTHAM Avenue',
    city: 'Cambridge',
    beds: '(1+0)',
    baths: '(1+0)',
    sqftAboveGround: 615,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 525111,
    discountFromAverageHomePrice: '24%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40177734',
    mlsUrl: '',
    status: 'A',
    currentPrice: 499999,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '126 CEDAR Street S',
    city: 'Kitchener',
    beds: '(3+0)',
    baths: '(1+1)',
    sqftAboveGround: 1150,
    sqftBelowGround: null,
    daysOnMarket: 1,
    averageHomePriceInTheArea: 710833.3333333334,
    discountFromAverageHomePrice: '30%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40176538',
    mlsUrl: '',
    status: 'A',
    currentPrice: 699900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '454 BOLINGBROOKE Place',
    city: 'Waterloo',
    beds: '(3+1)',
    baths: '(2+0)',
    sqftAboveGround: 1130,
    sqftBelowGround: 1130,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 915250,
    discountFromAverageHomePrice: '24%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40175803',
    mlsUrl: '',
    status: 'A',
    currentPrice: 750000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '43 RAMSAY Avenue',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1100,
    sqftBelowGround: 900,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 1062222.2222222222,
    discountFromAverageHomePrice: '29%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40178344',
    mlsUrl: '',
    status: 'A',
    currentPrice: 749900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '260 SIENNA Crescent',
    city: 'Kitchener',
    beds: '(3+0)',
    baths: '(1+1)',
    sqftAboveGround: 1740,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 962442.8571428572,
    discountFromAverageHomePrice: '22%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40178511',
    mlsUrl: '',
    status: 'A',
    currentPrice: 675000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '189 WEDGEWOOD Drive',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1193,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 913001.1428571428,
    discountFromAverageHomePrice: '26%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40176829',
    mlsUrl: '',
    status: 'A',
    currentPrice: 699900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '412 CARSON Drive',
    city: 'Kitchener',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1106,
    sqftBelowGround: 800,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 1036000,
    discountFromAverageHomePrice: '32%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40172803',
    mlsUrl: '',
    status: 'A',
    currentPrice: 700000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '8 CLIFFSIDE Court',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+1)',
    sqftAboveGround: 2104,
    sqftBelowGround: 879,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 919583.3333333334,
    discountFromAverageHomePrice: '24%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40175204',
    mlsUrl: '',
    status: 'A',
    currentPrice: 999000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '430 KELSO Drive',
    city: 'Waterloo',
    beds: '(4+1)',
    baths: '(3+1)',
    sqftAboveGround: 2313,
    sqftBelowGround: 946,
    daysOnMarket: 1,
    averageHomePriceInTheArea: 1300000,
    discountFromAverageHomePrice: '23%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40175803',
    mlsUrl: '',
    status: 'A',
    currentPrice: 750000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '43 RAMSAY Avenue',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1100,
    sqftBelowGround: 900,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 1074625,
    discountFromAverageHomePrice: '30%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40176727',
    mlsUrl: '',
    status: 'A',
    currentPrice: 829900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '172 HARDCASTLE Drive',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+2)',
    sqftAboveGround: 1350,
    sqftBelowGround: 600,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 1078216.6666666667,
    discountFromAverageHomePrice: '23%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40177734',
    mlsUrl: '',
    status: 'A',
    currentPrice: 499999,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '126 CEDAR Street S',
    city: 'Kitchener',
    beds: '(3+0)',
    baths: '(1+1)',
    sqftAboveGround: 1150,
    sqftBelowGround: null,
    daysOnMarket: 1,
    averageHomePriceInTheArea: 710833.3333333334,
    discountFromAverageHomePrice: '30%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40178344',
    mlsUrl: '',
    status: 'A',
    currentPrice: 749900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '260 SIENNA Crescent',
    city: 'Kitchener',
    beds: '(3+0)',
    baths: '(1+1)',
    sqftAboveGround: 1740,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 986566.6666666666,
    discountFromAverageHomePrice: '24%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40178511',
    mlsUrl: '',
    status: 'A',
    currentPrice: 675000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '189 WEDGEWOOD Drive',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1193,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 850411.1111111111,
    discountFromAverageHomePrice: '21%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40177643',
    mlsUrl: '',
    status: 'A',
    currentPrice: 549900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '831 SHERRING Street',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1656,
    sqftBelowGround: null,
    daysOnMarket: 1,
    averageHomePriceInTheArea: 688488.5,
    discountFromAverageHomePrice: '20%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40161666',
    mlsUrl: '',
    status: 'A',
    currentPrice: 700000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '11 GLOUCESTER Court',
    city: 'Kitchener',
    beds: '(3+1)',
    baths: '(3+1)',
    sqftAboveGround: 1962,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 941400,
    discountFromAverageHomePrice: '26%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40178261',
    mlsUrl: '',
    status: 'A',
    currentPrice: 875000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '711 WESTMOUNT Road W',
    city: 'Kitchener',
    beds: '(2+0)',
    baths: '(3+0)',
    sqftAboveGround: 1761,
    sqftBelowGround: 747,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 2300000,
    discountFromAverageHomePrice: '62%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40176618',
    mlsUrl: '',
    status: 'A',
    currentPrice: 869000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '269 RIDGEMERE Court',
    city: 'Kitchener',
    beds: '(3+1)',
    baths: '(3+0)',
    sqftAboveGround: 1715,
    sqftBelowGround: 1100,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 1271500,
    discountFromAverageHomePrice: '32%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40176252',
    mlsUrl: '',
    status: 'A',
    currentPrice: 535000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '10 HARVEY Street',
    city: 'Cambridge',
    beds: '(2+0)',
    baths: '(1+1)',
    sqftAboveGround: 715,
    sqftBelowGround: 600,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 696750,
    discountFromAverageHomePrice: '23%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40176671',
    mlsUrl: '',
    status: 'A',
    currentPrice: 649900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '114 WILLIAM Street W',
    city: 'Waterloo',
    beds: '(2+0)',
    baths: '(1+2)',
    sqftAboveGround: 952,
    sqftBelowGround: 84,
    daysOnMarket: 1,
    averageHomePriceInTheArea: 1078333.3333333333,
    discountFromAverageHomePrice: '40%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40176727',
    mlsUrl: '',
    status: 'A',
    currentPrice: 829900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '172 HARDCASTLE Drive',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+2)',
    sqftAboveGround: 1350,
    sqftBelowGround: 600,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 1102333.3333333333,
    discountFromAverageHomePrice: '25%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40175204',
    mlsUrl: '',
    status: 'A',
    currentPrice: 999000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '430 KELSO Drive',
    city: 'Waterloo',
    beds: '(4+1)',
    baths: '(3+1)',
    sqftAboveGround: 2313,
    sqftBelowGround: 946,
    daysOnMarket: 1,
    averageHomePriceInTheArea: 1300000,
    discountFromAverageHomePrice: '23%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40178261',
    mlsUrl: '',
    status: 'A',
    currentPrice: 875000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '711 WESTMOUNT Road W',
    city: 'Kitchener',
    beds: '(2+0)',
    baths: '(3+0)',
    sqftAboveGround: 1761,
    sqftBelowGround: 747,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 1637500,
    discountFromAverageHomePrice: '47%',
  },
  {
    distanceFromSearch: '0.3km',
    mls: '40178511',
    mlsUrl: '',
    status: 'A',
    currentPrice: 675000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '189 WEDGEWOOD Drive',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1193,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 880726.4285714285,
    discountFromAverageHomePrice: '23%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40176618',
    mlsUrl: '',
    status: 'A',
    currentPrice: 869000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '269 RIDGEMERE Court',
    city: 'Kitchener',
    beds: '(3+1)',
    baths: '(3+0)',
    sqftAboveGround: 1715,
    sqftBelowGround: 1100,
    daysOnMarket: 5,
    averageHomePriceInTheArea: 1333333.3333333333,
    discountFromAverageHomePrice: '35%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40176252',
    mlsUrl: '',
    status: 'A',
    currentPrice: 535000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '10 HARVEY Street',
    city: 'Cambridge',
    beds: '(2+0)',
    baths: '(1+1)',
    sqftAboveGround: 715,
    sqftBelowGround: 600,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 712331.8888888889,
    discountFromAverageHomePrice: '25%',
  },
  {
    distanceFromSearch: '0.0km',
    mls: '40173460',
    mlsUrl: '',
    status: 'A',
    currentPrice: 674900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '12 VETERANS Way',
    city: 'Cambridge',
    beds: '(3+2)',
    baths: '(4+0)',
    sqftAboveGround: 1845,
    sqftBelowGround: null,
    daysOnMarket: 1,
    averageHomePriceInTheArea: 1027277.5,
    discountFromAverageHomePrice: '34%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40161666',
    mlsUrl: '',
    status: 'A',
    currentPrice: 700000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '11 GLOUCESTER Court',
    city: 'Kitchener',
    beds: '(3+1)',
    baths: '(3+1)',
    sqftAboveGround: 1962,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 906000,
    discountFromAverageHomePrice: '23%',
  },
  {
    distanceFromSearch: '0.0km',
    mls: '40172803',
    mlsUrl: '',
    status: 'A',
    currentPrice: 700000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '8 CLIFFSIDE Court',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+1)',
    sqftAboveGround: 2104,
    sqftBelowGround: 879,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 966833.3333333334,
    discountFromAverageHomePrice: '28%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40177520',
    mlsUrl: '',
    status: 'A',
    currentPrice: 669000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '237A THISTLEGLEN Place',
    city: 'Waterloo',
    beds: '(3+0)',
    baths: '(1+1)',
    sqftAboveGround: 1177,
    sqftBelowGround: 230,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 860500,
    discountFromAverageHomePrice: '22%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40175803',
    mlsUrl: '',
    status: 'A',
    currentPrice: 750000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '43 RAMSAY Avenue',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1100,
    sqftBelowGround: 900,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 1061650,
    discountFromAverageHomePrice: '29%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40176829',
    mlsUrl: '',
    status: 'A',
    currentPrice: 699900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '412 CARSON Drive',
    city: 'Kitchener',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1106,
    sqftBelowGround: 800,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 1036000,
    discountFromAverageHomePrice: '32%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40178344',
    mlsUrl: '',
    status: 'A',
    currentPrice: 749900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '260 SIENNA Crescent',
    city: 'Kitchener',
    beds: '(3+0)',
    baths: '(1+1)',
    sqftAboveGround: 1740,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 969183.3333333334,
    discountFromAverageHomePrice: '23%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40177643',
    mlsUrl: '',
    status: 'A',
    currentPrice: 549900,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '831 SHERRING Street',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(2+0)',
    sqftAboveGround: 1656,
    sqftBelowGround: null,
    daysOnMarket: 1,
    averageHomePriceInTheArea: 702325.6666666666,
    discountFromAverageHomePrice: '22%',
  },
  {
    distanceFromSearch: '0.1km',
    mls: '40175735',
    mlsUrl: '',
    status: 'A',
    currentPrice: 500000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '69 FRANCIS Street',
    city: 'Cambridge',
    beds: '(3+0)',
    baths: '(1+0)',
    sqftAboveGround: 1260,
    sqftBelowGround: null,
    daysOnMarket: 0,
    averageHomePriceInTheArea: 659375,
    discountFromAverageHomePrice: '24%',
  },
  {
    distanceFromSearch: '0.2km',
    mls: '40170498',
    mlsUrl: '',
    status: 'A',
    currentPrice: 525000,
    subType: 'HOUSE',
    commonInterest: 'Freehold/None',
    address: '53 FIRST Avenue',
    city: 'Cambridge',
    beds: '(4+0)',
    baths: '(2+0)',
    sqftAboveGround: 1217,
    sqftBelowGround: null,
    daysOnMarket: 4,
    averageHomePriceInTheArea: 659375,
    discountFromAverageHomePrice: '20%',
  },
];
